/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crms;

import java.awt.Component;
import java.awt.Container;
import java.awt.Window;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Orlon
 */
public class AddC extends javax.swing.JPanel {

    /**
     * Creates new form AddC
     */
    JFileChooser chooser;
    PreparedStatement pst;
    private boolean blank=true;

    public AddC() {
        initComponents();

        try {
            CID.setText("#" + currentID());
            pst = Database.getConnection().prepareStatement("insert into mtblCriminals values(null,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
        } catch (SQLException ex) {
            Logger.getLogger(AddC.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void setAll() {
        try {
            Date dateFromDateChooser = tdob.getDate();
            Date dateFromDateChooser1 = tArrestdate.getDate();
            String dateString = String.format("%1$tY-%1$tm-%1$td", dateFromDateChooser);
            String dateString1 = String.format("%1$tY-%1$tm-%1$td", dateFromDateChooser1);
            storeImage();
            // pst.setBinaryStream(2,);
            pst.setString(3, dateString1==null?"9999-9-19":dateString1);
            pst.setString(4, tFirst.getText());
            pst.setString(5, tMiddle.getText());
            pst.setString(6, tLast.getText());
            pst.setString(7, dateString==null?"9999-9-19":dateString1);
            pst.setString(8, cState.getSelectedItem().toString());
            pst.setString(9, cCity.getSelectedItem().toString());
            pst.setString(10, tAddress.getText());
            pst.setString(11, rMale.isSelected() ? "M" : rFemale.isSelected() ? "F" : "U");
            pst.setString(12, cMarital.getSelectedItem().toString());
            pst.setString(13, tColor.getText());
            pst.setString(14, cHair.getSelectedItem().toString());
            pst.setString(15, cBloodgroup.getSelectedItem().toString());
            Double Height = Double.parseDouble(tFoot.getText() + "." + tInch.getText()+"0");
            pst.setDouble(16, Height);
            pst.setDouble(17, Double.parseDouble(tWeight.getText()+"0"));
            pst.setString(18, tEyes.getText());
            pst.setString(19, tFacility.getText());
            pst.setString(20, tSection.getText());
            pst.setString(21, tCell.getText());
            pst.setString(22, tAdditional.getText());
            pst.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(AddC.class.getName()).log(Level.SEVERE, null, ex);
        }
        clearAll();
        CID.setText("#" + currentID());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        lMiddle = new javax.swing.JLabel();
        cMarital = new javax.swing.JComboBox();
        rFemale = new javax.swing.JRadioButton();
        rMale = new javax.swing.JRadioButton();
        lState = new javax.swing.JLabel();
        cState = new javax.swing.JComboBox();
        tLast = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tAddress = new javax.swing.JTextArea();
        lName = new javax.swing.JLabel();
        ldob = new javax.swing.JLabel();
        lMarital = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bCrimes = new javax.swing.JButton();
        tFirst = new javax.swing.JTextField();
        lGender = new javax.swing.JLabel();
        tMiddle = new javax.swing.JTextField();
        lFirst = new javax.swing.JLabel();
        lLast = new javax.swing.JLabel();
        lAddress = new javax.swing.JLabel();
        lCity = new javax.swing.JLabel();
        cCity = new javax.swing.JComboBox();
        tdob = new com.toedter.calendar.JDateChooser();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        tFacility = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tAdditional = new javax.swing.JTextArea();
        lSection = new javax.swing.JLabel();
        lFacility = new javax.swing.JLabel();
        lAdditional = new javax.swing.JLabel();
        tCell = new javax.swing.JTextField();
        tSection = new javax.swing.JTextField();
        lCell = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        bClear = new javax.swing.JButton();
        bSave = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        bBrowse = new javax.swing.JButton();
        tArrestdate = new com.toedter.calendar.JDateChooser();
        bRemove = new javax.swing.JButton();
        IMAGE = new javax.swing.JLabel();
        lArrest = new javax.swing.JLabel();
        CID = new javax.swing.JTextField();
        lId = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lColor = new javax.swing.JLabel();
        tWeight = new javax.swing.JTextField();
        lInch = new javax.swing.JLabel();
        tInch = new javax.swing.JTextField();
        lHeight = new javax.swing.JLabel();
        tColor = new javax.swing.JTextField();
        lFoot = new javax.swing.JLabel();
        lHair = new javax.swing.JLabel();
        tFoot = new javax.swing.JTextField();
        tEyes = new javax.swing.JTextField();
        cHair = new javax.swing.JComboBox();
        lWeight = new javax.swing.JLabel();
        lBloodgroup = new javax.swing.JLabel();
        lKg = new javax.swing.JLabel();
        cBloodgroup = new javax.swing.JComboBox();
        lEyes = new javax.swing.JLabel();

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lMiddle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lMiddle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lMiddle.setText("Middle");

        cMarital.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cMarital.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Single", "Married", "Widowed", "Separated", "Divorced" }));
        cMarital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cMaritalActionPerformed(evt);
            }
        });

        buttonGroup1.add(rFemale);
        rFemale.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rFemale.setText("Female");

        buttonGroup1.add(rMale);
        rMale.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rMale.setText("Male");

        lState.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lState.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lState.setText("State ");

        cState.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cState.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cStateActionPerformed(evt);
            }
        });

        tLast.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tLastActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        tAddress.setColumns(20);
        tAddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tAddress.setLineWrap(true);
        tAddress.setRows(5);
        tAddress.setWrapStyleWord(true);
        jScrollPane1.setViewportView(tAddress);

        lName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lName.setText("Name");

        ldob.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ldob.setText("Date of Birth");

        lMarital.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lMarital.setText("Marital Status ");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setEnabled(false);

        bCrimes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bCrimes.setText("Crimes & Punishments");
        bCrimes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrimesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bCrimes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bCrimes)
                .addContainerGap())
        );

        tFirst.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFirstActionPerformed(evt);
            }
        });

        lGender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lGender.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lGender.setText("Gender ");

        tMiddle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tMiddle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tMiddleActionPerformed(evt);
            }
        });

        lFirst.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lFirst.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lFirst.setText("First");

        lLast.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lLast.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lLast.setText("Last");
        lLast.setToolTipText("");

        lAddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lAddress.setText("Address ");

        lCity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lCity.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lCity.setText("City ");

        cCity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cCity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tdob.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Unknown");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ldob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lMarital, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lFirst, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tFirst, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cMarital, 0, 160, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(tdob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lMiddle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(tMiddle))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tLast, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lLast, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lGender, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(lState, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lCity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cState, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cCity, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rMale)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rFemale)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton1)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lName))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lFirst)
                            .addComponent(lMiddle)
                            .addComponent(lLast))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tFirst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tMiddle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tLast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tdob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ldob)
                        .addComponent(lState)
                        .addComponent(cState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lCity)
                            .addComponent(cCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rMale)
                            .addComponent(rFemale)
                            .addComponent(lGender)
                            .addComponent(jRadioButton1)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lAddress))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cMarital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lMarital, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tFacility.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tAdditional.setColumns(20);
        tAdditional.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tAdditional.setLineWrap(true);
        tAdditional.setRows(5);
        jScrollPane2.setViewportView(tAdditional);

        lSection.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lSection.setText("Section");

        lFacility.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lFacility.setText("Facility");

        lAdditional.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lAdditional.setText("Additional Information");

        tCell.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tSection.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lCell.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lCell.setText("Cell");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lFacility)
                    .addComponent(lSection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lCell, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tCell, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(tSection, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tFacility, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(91, 91, 91)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lAdditional)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tFacility, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lFacility))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lSection)
                    .addComponent(tSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCell)
                    .addComponent(tCell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(lAdditional)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        bClear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bClear.setText("Clear");
        bClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bClearActionPerformed(evt);
            }
        });

        bSave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bSave.setText("Save");
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bSave, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addComponent(bClear, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bClear)
                    .addComponent(bSave))
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bBrowse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bBrowse.setText("Browse");
        bBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBrowseActionPerformed(evt);
            }
        });

        bRemove.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bRemove.setText("Remove");
        bRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRemoveActionPerformed(evt);
            }
        });

        IMAGE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/insignia.alpha.png"))); // NOI18N

        lArrest.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lArrest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lArrest.setText("Arrest Date");

        CID.setEditable(false);
        CID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CIDActionPerformed(evt);
            }
        });

        lId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lId.setText("ID");
        lId.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CID, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IMAGE, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tArrestdate, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(bBrowse)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(bRemove))
                                    .addComponent(lArrest, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IMAGE, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bBrowse)
                    .addComponent(bRemove))
                .addGap(42, 42, 42)
                .addComponent(lArrest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tArrestdate, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lColor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lColor.setText("Color");

        tWeight.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lInch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lInch.setText("inch");

        tInch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tInch.setText("0");

        lHeight.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lHeight.setText("Height");

        tColor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tColorActionPerformed(evt);
            }
        });

        lFoot.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lFoot.setText("ft.");

        lHair.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lHair.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lHair.setText("Hair");

        tFoot.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tFoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFootActionPerformed(evt);
            }
        });

        tEyes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cHair.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cHair.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lWeight.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lWeight.setText("Weight");

        lBloodgroup.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lBloodgroup.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lBloodgroup.setText("Blood Group ");

        lKg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lKg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lKg.setText("Kg.");

        cBloodgroup.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cBloodgroup.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A +ve", "A -ve", "B +ve", "B -ve", "O +ve", "O -ve", "AB +ve", "AB -ve" }));
        cBloodgroup.setToolTipText("");
        cBloodgroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBloodgroupActionPerformed(evt);
            }
        });

        lEyes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lEyes.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lEyes.setText("Eyes ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lColor)
                    .addComponent(lHeight))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(tFoot, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lFoot)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tInch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lInch))
                    .addComponent(tColor, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lHair, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cHair, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lBloodgroup, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lWeight)
                        .addGap(18, 18, 18)
                        .addComponent(tWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lKg, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lEyes, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cBloodgroup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tEyes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lColor)
                        .addComponent(tColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lBloodgroup)
                        .addComponent(cBloodgroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cHair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lHair)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lHeight)
                        .addComponent(tFoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lFoot)
                        .addComponent(tInch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lInch))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tEyes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lEyes)
                        .addComponent(lKg))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lWeight)
                        .addComponent(tWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(5, 5, 5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBrowseActionPerformed
        // TODO add your handling code here:
        chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "JPG & PNG Images", "jpg", "png");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            IMAGE.setIcon(new ImageIcon("" + chooser.getSelectedFile()));
        }
        else
        blank=false;
    }//GEN-LAST:event_bBrowseActionPerformed

    private void tMiddleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tMiddleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tMiddleActionPerformed

    private void tLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tLastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tLastActionPerformed

    private void tFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFirstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFirstActionPerformed

    private void bRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRemoveActionPerformed
        // TODO add your handling code here:
        IMAGE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/insignia.alpha.png")));
        blank=true;
    }//GEN-LAST:event_bRemoveActionPerformed

    private void cStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cStateActionPerformed

    private void bClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bClearActionPerformed
        // TODO add your handling code here
        clearAll();
    }//GEN-LAST:event_bClearActionPerformed

    private void cMaritalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cMaritalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cMaritalActionPerformed

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
        setAll();
    }//GEN-LAST:event_bSaveActionPerformed

    private void bCrimesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrimesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bCrimesActionPerformed

    private void CIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CIDActionPerformed

    private void tColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tColorActionPerformed

    private void tFootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFootActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFootActionPerformed

    private void cBloodgroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBloodgroupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cBloodgroupActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CID;
    private javax.swing.JLabel IMAGE;
    private javax.swing.JButton bBrowse;
    private javax.swing.JButton bClear;
    private javax.swing.JButton bCrimes;
    private javax.swing.JButton bRemove;
    private javax.swing.JButton bSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cBloodgroup;
    private javax.swing.JComboBox cCity;
    private javax.swing.JComboBox cHair;
    private javax.swing.JComboBox cMarital;
    private javax.swing.JComboBox cState;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lAdditional;
    private javax.swing.JLabel lAddress;
    private javax.swing.JLabel lArrest;
    private javax.swing.JLabel lBloodgroup;
    private javax.swing.JLabel lCell;
    private javax.swing.JLabel lCity;
    private javax.swing.JLabel lColor;
    private javax.swing.JLabel lEyes;
    private javax.swing.JLabel lFacility;
    private javax.swing.JLabel lFirst;
    private javax.swing.JLabel lFoot;
    private javax.swing.JLabel lGender;
    private javax.swing.JLabel lHair;
    private javax.swing.JLabel lHeight;
    private javax.swing.JLabel lId;
    private javax.swing.JLabel lInch;
    private javax.swing.JLabel lKg;
    private javax.swing.JLabel lLast;
    private javax.swing.JLabel lMarital;
    private javax.swing.JLabel lMiddle;
    private javax.swing.JLabel lName;
    private javax.swing.JLabel lSection;
    private javax.swing.JLabel lState;
    private javax.swing.JLabel lWeight;
    private javax.swing.JLabel ldob;
    private javax.swing.JRadioButton rFemale;
    private javax.swing.JRadioButton rMale;
    private javax.swing.JTextArea tAdditional;
    private javax.swing.JTextArea tAddress;
    private com.toedter.calendar.JDateChooser tArrestdate;
    private javax.swing.JTextField tCell;
    private javax.swing.JTextField tColor;
    private javax.swing.JTextField tEyes;
    private javax.swing.JTextField tFacility;
    private javax.swing.JTextField tFirst;
    private javax.swing.JTextField tFoot;
    private javax.swing.JTextField tInch;
    private javax.swing.JTextField tLast;
    private javax.swing.JTextField tMiddle;
    private javax.swing.JTextField tSection;
    private javax.swing.JTextField tWeight;
    private com.toedter.calendar.JDateChooser tdob;
    // End of variables declaration//GEN-END:variables

    private void storeImage(){
            File file;
            String s="null";
            byte[] absent = s.getBytes();
            String filePath = null;
            try{
            if (blank==true) {
               pst.setBytes(1,absent);
               pst.setInt(2, 1);
            }
            else{
                file = chooser.getSelectedFile();
            
            if (file != null) {
                filePath = file.getPath();
            }

            if (filePath != null) {
                    FileInputStream fileInputStream = new FileInputStream(filePath);
                    byte b[] = new byte[fileInputStream.available()];
                    fileInputStream.read(b);
                    fileInputStream.close();
                    //pst.setObject(1, jTextField1.getText());
                
                    pst.setBytes(1, b);
                    pst.setInt(2, 1);
            }
            }
            }
            catch(Exception e)
            {
                System.out.println(e.getMessage());
            }
    }

    private int currentID() {
        //To change body of generated methods, choose Tools | Templates.
        int currentid = 0;
        try {
            ResultSet rs = Database.getStatement().executeQuery("Select count(cid) from mtblCriminals");
            rs.next();
            currentid = rs.getInt(1);
        } catch (SQLException ex) {
            Logger.getLogger(AddC.class.getName()).log(Level.SEVERE, null, ex);
        }
        return (currentid + 1);
    }

    private void clearAll() {
        JTextField tfield = null;
        JPanel tJpanel = null;
        for (Component c : this.getComponents()) {
            //  System.out.println(c);
            if (c.getClass().toString().contains("javax.swing.JPanel")) {
                tJpanel = (JPanel) c;
                for (Component d : tJpanel.getComponents()) {
                    if (d.getClass().toString().contains("javax.swing.JTextField")) {
                        tfield = (JTextField) d;
                        tfield.setText("");
                    }
                }
            }
            tAddress.setText("");
            tAdditional.setText("");
            tdob.setDate(null);
            tArrestdate.setDate(null);
            cState.setSelectedIndex(0);
            cCity.setSelectedIndex(0);
            cMarital.setSelectedIndex(0);
            cHair.setSelectedIndex(0);
            cBloodgroup.setSelectedIndex(0);

        }
        CID.setText("#" + currentID());
    }

}
