/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crms;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Toolkit;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Orlon
 */
public class Show extends javax.swing.JFrame {
    int cid;
    /**
     * Creates new form Printing
     */
    public Show(int cid) {
        initComponents();
        this.cid=cid;
        SetAll();
        setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lSection = new javax.swing.JLabel();
        lFacility = new javax.swing.JLabel();
        lAdditional = new javax.swing.JLabel();
        lCell = new javax.swing.JLabel();
        lName15 = new javax.swing.JLabel();
        lName16 = new javax.swing.JLabel();
        lName17 = new javax.swing.JLabel();
        lName18 = new javax.swing.JLabel();
        bSearch = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lState = new javax.swing.JLabel();
        lName = new javax.swing.JLabel();
        ldob = new javax.swing.JLabel();
        lMarital = new javax.swing.JLabel();
        lGender = new javax.swing.JLabel();
        lAddress = new javax.swing.JLabel();
        lCity = new javax.swing.JLabel();
        tMiddle = new javax.swing.JLabel();
        tLast = new javax.swing.JLabel();
        tDob = new javax.swing.JLabel();
        tCity = new javax.swing.JLabel();
        tState = new javax.swing.JLabel();
        tMarital = new javax.swing.JLabel();
        tGender = new javax.swing.JLabel();
        tFirst = new javax.swing.JLabel();
        lEyes = new javax.swing.JLabel();
        tColor = new javax.swing.JLabel();
        tHair = new javax.swing.JLabel();
        tBlood = new javax.swing.JLabel();
        tHeight = new javax.swing.JLabel();
        lColor = new javax.swing.JLabel();
        tWeight = new javax.swing.JLabel();
        lHeight = new javax.swing.JLabel();
        tEyes = new javax.swing.JLabel();
        lHair = new javax.swing.JLabel();
        lWeight = new javax.swing.JLabel();
        lBloodgroup = new javax.swing.JLabel();
        lKg = new javax.swing.JLabel();
        lSection1 = new javax.swing.JLabel();
        lFacility1 = new javax.swing.JLabel();
        lAdditional1 = new javax.swing.JLabel();
        lCell1 = new javax.swing.JLabel();
        tFacility = new javax.swing.JLabel();
        tCell = new javax.swing.JLabel();
        tSection = new javax.swing.JLabel();
        lId = new javax.swing.JLabel();
        tImage = new javax.swing.JLabel();
        tId = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tAdditional = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tAddress = new javax.swing.JTextArea();
        bSearch1 = new javax.swing.JButton();

        lSection.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lSection.setText("Section");

        lFacility.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lFacility.setText("Facility");

        lAdditional.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lAdditional.setText("Additional Information");

        lCell.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lCell.setText("Cell");

        lName15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lName15.setText("Name");

        lName16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lName16.setText("Name");

        lName17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lName17.setText("Name");

        lName18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lName18.setText("Name");

        bSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bSearch.setText("Search");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Criminal Information");
        setFocusCycleRoot(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lState.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lState.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lState.setText("State ");
        lState.setToolTipText("");

        lName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lName.setText("Name");
        lName.setToolTipText("");

        ldob.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ldob.setText("Date of Birth");
        ldob.setToolTipText("");

        lMarital.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lMarital.setText("Marital Status ");
        lMarital.setToolTipText("");

        lGender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lGender.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lGender.setText("Gender ");
        lGender.setToolTipText("");

        lAddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lAddress.setText("Address ");
        lAddress.setToolTipText("");

        lCity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lCity.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lCity.setText("City ");
        lCity.setToolTipText("");

        tMiddle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tMiddle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tMiddle.setText("Ramesh");
        tMiddle.setToolTipText("");

        tLast.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tLast.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tLast.setText("Parab");
        tLast.setToolTipText("");

        tDob.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tDob.setText("1-12-1995");
        tDob.setToolTipText("");

        tCity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tCity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tCity.setText("Mumbai");
        tCity.setToolTipText("");

        tState.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tState.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tState.setText("Maharashtra");
        tState.setToolTipText("");

        tMarital.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tMarital.setText("Single");
        tMarital.setToolTipText("");

        tGender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tGender.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tGender.setText("Male");
        tGender.setToolTipText("");

        tFirst.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tFirst.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tFirst.setText("Sushant");
        tFirst.setToolTipText("");

        lEyes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lEyes.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lEyes.setText("Eyes ");
        lEyes.setToolTipText("");

        tColor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tColor.setText("Brown");
        tColor.setToolTipText("");

        tHair.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tHair.setText("Straight");
        tHair.setToolTipText("");

        tBlood.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tBlood.setText("A+");
        tBlood.setToolTipText("");

        tHeight.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tHeight.setText("5'9");
        tHeight.setToolTipText("");

        lColor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lColor.setText("Color");
        lColor.setToolTipText("");

        tWeight.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tWeight.setForeground(new java.awt.Color(0, 51, 153));
        tWeight.setText("60");
        tWeight.setToolTipText("");

        lHeight.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lHeight.setText("Height");
        lHeight.setToolTipText("");

        tEyes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tEyes.setText("Black");
        tEyes.setToolTipText("");

        lHair.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lHair.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lHair.setText("Hair");
        lHair.setToolTipText("");

        lWeight.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lWeight.setText("Weight");
        lWeight.setToolTipText("");

        lBloodgroup.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lBloodgroup.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lBloodgroup.setText("Blood Group ");
        lBloodgroup.setToolTipText("");

        lKg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lKg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lKg.setText("Kg.");
        lKg.setToolTipText("");

        lSection1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lSection1.setText("Section");
        lSection1.setToolTipText("");

        lFacility1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lFacility1.setText("Facility");
        lFacility1.setToolTipText("");

        lAdditional1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lAdditional1.setText("Additional Information");
        lAdditional1.setToolTipText("");

        lCell1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lCell1.setText("Cell");
        lCell1.setToolTipText("");

        tFacility.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tFacility.setText("Prison ");
        tFacility.setToolTipText("");

        tCell.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tCell.setText("323");
        tCell.setToolTipText("");

        tSection.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tSection.setText("A");
        tSection.setToolTipText("");

        lId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lId.setText("ID");
        lId.setToolTipText("");
        lId.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        tImage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tImage.setForeground(new java.awt.Color(0, 51, 153));
        tImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Settings.png"))); // NOI18N
        tImage.setToolTipText("");

        tId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tId.setText("#1");
        tId.setToolTipText("");

        jScrollPane1.setForeground(new java.awt.Color(0, 51, 153));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setEnabled(false);
        jScrollPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tAdditional.setEditable(false);
        tAdditional.setColumns(20);
        tAdditional.setLineWrap(true);
        tAdditional.setRows(5);
        tAdditional.setText("dkflmdsklfmkldsmfkldmslfmkdsmfkmdsklfmkldsfmkldsmklfmdsklmfkldsmfklmdsklfmdsklmflkdsmfklmdsklfmds");
        tAdditional.setBorder(null);
        jScrollPane1.setViewportView(tAdditional);

        jScrollPane2.setForeground(new java.awt.Color(0, 51, 153));
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane2.setEnabled(false);
        jScrollPane2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tAddress.setEditable(false);
        tAddress.setColumns(20);
        tAddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tAddress.setLineWrap(true);
        tAddress.setRows(5);
        tAddress.setBorder(null);
        jScrollPane2.setViewportView(tAddress);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lCell1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lFacility1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                            .addComponent(lSection1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addComponent(lKg, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lEyes, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tEyes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(jScrollPane1)
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lHeight)
                            .addComponent(lColor))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tHeight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tColor, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                                    .addComponent(tFacility, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lHair, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lWeight))
                                        .addGap(21, 21, 21)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(tHair, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lBloodgroup, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(tBlood, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(tWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(lAdditional1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tSection, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tCell, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lId)
                                .addGap(18, 18, 18)
                                .addComponent(tId, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ldob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lMarital, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lName, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tMarital, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(83, 83, 83)
                                        .addComponent(tFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tDob, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(lGender, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tGender, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tMiddle, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tLast, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lCity, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(lState, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(3, 3, 3)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tCity, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tState, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(tImage, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tImage, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lId)
                    .addComponent(tId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lName)
                    .addComponent(tFirst)
                    .addComponent(tMiddle)
                    .addComponent(tLast))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lState)
                    .addComponent(tDob)
                    .addComponent(ldob)
                    .addComponent(tState))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCity)
                    .addComponent(tCity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lAddress)
                        .addGap(135, 135, 135))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lGender)
                                    .addComponent(tGender))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lMarital, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tMarital))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tColor, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lColor)
                                .addComponent(tHair)
                                .addComponent(lBloodgroup)
                                .addComponent(tBlood)
                                .addComponent(lHair)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lHeight)
                            .addComponent(lWeight)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tHeight)
                                .addComponent(tEyes)
                                .addComponent(tWeight)
                                .addComponent(lEyes)
                                .addComponent(lKg)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tFacility)
                            .addComponent(lAdditional1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tSection)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tCell))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lFacility1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lSection1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lCell1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bSearch1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bSearch1.setText("Print");
        bSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSearch1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSearch1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(bSearch1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSearch1ActionPerformed
       // PrinterJob pj = PrinterJob.getPrinterJob();
        PrintUtilities p=new PrintUtilities(jPanel1);
        p.print();
    }//GEN-LAST:event_bSearch1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bSearch;
    private javax.swing.JButton bSearch1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lAdditional;
    private javax.swing.JLabel lAdditional1;
    private javax.swing.JLabel lAddress;
    private javax.swing.JLabel lBloodgroup;
    private javax.swing.JLabel lCell;
    private javax.swing.JLabel lCell1;
    private javax.swing.JLabel lCity;
    private javax.swing.JLabel lColor;
    private javax.swing.JLabel lEyes;
    private javax.swing.JLabel lFacility;
    private javax.swing.JLabel lFacility1;
    private javax.swing.JLabel lGender;
    private javax.swing.JLabel lHair;
    private javax.swing.JLabel lHeight;
    private javax.swing.JLabel lId;
    private javax.swing.JLabel lKg;
    private javax.swing.JLabel lMarital;
    private javax.swing.JLabel lName;
    private javax.swing.JLabel lName15;
    private javax.swing.JLabel lName16;
    private javax.swing.JLabel lName17;
    private javax.swing.JLabel lName18;
    private javax.swing.JLabel lSection;
    private javax.swing.JLabel lSection1;
    private javax.swing.JLabel lState;
    private javax.swing.JLabel lWeight;
    private javax.swing.JLabel ldob;
    private javax.swing.JTextArea tAdditional;
    private javax.swing.JTextArea tAddress;
    private javax.swing.JLabel tBlood;
    private javax.swing.JLabel tCell;
    private javax.swing.JLabel tCity;
    private javax.swing.JLabel tColor;
    private javax.swing.JLabel tDob;
    private javax.swing.JLabel tEyes;
    private javax.swing.JLabel tFacility;
    private javax.swing.JLabel tFirst;
    private javax.swing.JLabel tGender;
    private javax.swing.JLabel tHair;
    private javax.swing.JLabel tHeight;
    private javax.swing.JLabel tId;
    private javax.swing.JLabel tImage;
    private javax.swing.JLabel tLast;
    private javax.swing.JLabel tMarital;
    private javax.swing.JLabel tMiddle;
    private javax.swing.JLabel tSection;
    private javax.swing.JLabel tState;
    private javax.swing.JLabel tWeight;
    // End of variables declaration//GEN-END:variables

    private void SetAll() {
        try {
            ResultSet rs=Database.getStatement().executeQuery("select * from mtblCriminals where cid="+cid);
           if(rs.next())
           {   
            tImage.setIcon(new ImageIcon(((new ImageIcon(rs.getBytes("image"))).getImage()).getScaledInstance(192, 192, java.awt.Image.SCALE_SMOOTH)));

              // tImage.setIcon(new ImageIcon(rs.getBytes("image")));
               tId.setText("#"+rs.getInt("cid"));
               tAdditional.setText(rs.getString("ai"));
               tAddress.setText(""+rs.getString("address"));
               tBlood.setText(rs.getString("bg"));
               tCell.setText(rs.getString("cell"));
               tCity.setText(rs.getString("city"));
               tColor.setText(rs.getString("color"));
               tDob.setText(rs.getString("dob"));
               tEyes.setText(rs.getString("eyes"));
               tFacility.setText(rs.getString("facility"));
               tFirst.setText(rs.getString("fname"));
               tGender.setText(rs.getString("gender"));
               tHair.setText(rs.getString("hair"));
               tHeight.setText(rs.getString("height"));
               //tId.setText(rs.getString("cell"));
               //t.setText(rs.getString("cell"));
               tLast.setText(rs.getString("lname"));
               tMarital.setText(rs.getString("mstatus"));
               tMiddle.setText(rs.getString("mname"));
               tSection.setText(rs.getString("section"));
               tState.setText(rs.getString("state"));
               tWeight.setText(rs.getString("weight"));
                       
               
           }
           
            
        } catch (SQLException ex) {
            Logger.getLogger(Show.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    String getJobName() {
            return tId.getText()+tFirst.getText()+tDob.getText();
    }
}
